"""Import smoke test for tools/nq_hud.py.

WHY THIS EXISTS: the rest of tools/tests imports only nq_signal and
nq_signal_log, so nq_hud.py was never imported by the suite at all — a syntax
error in it passed 455 green tests and was caught only by ruff. This closes
that gap.

It also pins the lazy-import discipline the module depends on: nq_hud must be
importable with no customtkinter, no tkinter, no gamma_tool, no gex_history_db
and no redis pulled in at module scope, so the window can still open (and
degrade visibly) when an engine import or the bus is unavailable.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))


def test_nq_hud_imports_cleanly():
    import tools.nq_hud as hud

    assert callable(hud.read_gamma)
    assert callable(hud.read_gamma_all)
    assert callable(hud.read_tape)
    assert callable(hud.build_pane)
    assert hud.ACTION_COLOR["LONG"] != hud.ACTION_COLOR["SHORT"]


def test_window_is_wide_enough_for_one_column_per_instrument():
    """The panes are packed side by side at a fixed PANE_WIDTH; a window sized
    for one would clip the second instrument entirely off the right edge — the
    same class of defect as the RISK panel that was cut off at "Entry"."""
    import tools.nq_hud as hud
    from tools.nq_instruments import INSTRUMENTS

    assert hud.WIN_WIDTH >= hud.PANE_WIDTH * len(INSTRUMENTS)


def test_nq_hud_pulls_in_no_heavy_dependencies_at_module_scope():
    heavy = {"customtkinter", "tkinter", "gamma_tool", "gex_history_db", "redis"}
    before = set(sys.modules)
    import tools.nq_hud  # noqa: F401
    leaked = {m.split(".")[0] for m in set(sys.modules) - before} & heavy
    assert not leaked, f"nq_hud imported {sorted(leaked)} at module scope"


def emitted_actions():
    """Every action build_verdict can actually produce.

    GENERATED by exercising the real function across every regime x phase x
    spot-position, not written down. A hardcoded list would still pass after a
    fifth action was added, which is precisely the case the consumers below
    need to be warned about.
    """
    from tools.nq_instruments import NQ
    from tools.nq_signal import PHASE_NOTE, build_verdict

    levels = {"call_wall": 100.0, "put_wall": 90.0, "pin": 95.0}
    return {build_verdict(regime, phase, spot, levels, atr, NQ)["action"]
            for regime in ("positive", "negative", "flip_zone", "unknown")
            for phase in PHASE_NOTE
            for spot in (101.0, 100.0, 95.0, 90.0, 89.0)
            for atr in (0.0, 10.0, 10_000.0)}


def test_the_action_vocabulary_is_the_four_we_think_it_is():
    """Three consumers switch on these strings by hand — the HUD's colour map,
    the NinjaScript panel's colour switch, and the NinjaScript's per-action
    SOUND switch. None of them can be reached from this suite (two are C#), so
    this pins the vocabulary itself: a fifth action fails here and names the
    places that need updating.
    """
    assert emitted_actions() == {"LONG", "SHORT", "WAIT", "STAND DOWN"}


def test_every_action_build_verdict_can_emit_has_a_colour():
    """A missing entry would paint the verdict in the fallback grey — legible,
    but it would silently lose the LONG/SHORT green-red distinction.
    """
    import tools.nq_hud as hud

    assert set(hud.ACTION_COLOR) == emitted_actions()


def test_actions_are_plain_uppercase_with_no_punctuation():
    """The C# sound switch matches these verbatim, including the space in
    "STAND DOWN". Anything with a character that is easy to mistype — an em
    dash, a colon — would silently fall through to no sound.
    """
    for action in emitted_actions():
        assert action == action.upper()
        assert all(c.isalpha() or c == " " for c in action), action
