#!/usr/bin/env bash
# Monthly refit of the swing factor model (Phase 6).
#
# Archives the current artifact + report under a DATED folder, re-runs the fit,
# and diffs the new report against the prior one so a decay is visible without
# anyone remembering to look.
#
# Why a script on a timer rather than a service job: the fit must stay
# un-importable by any service (it pulls 5 years of history for ~78 symbols and
# takes minutes), and dev runs with schedulers=False, so a service job would sit
# inert there.
#
# !! It refuses to run without the proxy. A fit against a dead proxy produces an
# artifact from whatever partial history it managed, which would then SHIP as the
# model -- worse than not refitting at all.
#
# The fit ships only if it passes the gate in config/swing_model.toml (coverage of
# the fit universe, out-of-sample IC above a floor). A refused fit is written as
# trade-analyzer/data/swing_model.rejected.json + its report, the live model is
# untouched, and this script exits 1.
#
# Scheduled by trading-<env>-swing-refit.timer (monthly, the 1st, at
# [slots.swing_refit] in config/sessions.toml), generated by
# deploy/systemd/generate_units.py. Until 2026-09-27 this comment described a
# timer that nobody installed, so the live model stayed at its 2026-08-22 fit.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
PY="$ROOT/.venv/bin/python"

[ -x "$PY" ] || { echo "[refit] no venv at $PY - aborting."; exit 1; }

# Resolve the proxy port from repo_paths rather than hardcoding it: a dev
# checkout borrows prod's proxy, so the number is environment-dependent.
PROXY_PORT="$("$PY" -c 'import sys;sys.path.insert(0,".");import repo_paths;print(repo_paths.PROXY_PORT)' 2>/dev/null || echo 8100)"
PROXY_HOST="$("$PY" -c 'import sys;sys.path.insert(0,".");import repo_paths;print(repo_paths.PROXY_HOST)' 2>/dev/null || echo 127.0.0.1)"

if ! "$PY" -c "import urllib.request;urllib.request.urlopen('http://${PROXY_HOST}:${PROXY_PORT}/health',timeout=5)" >/dev/null 2>&1; then
  echo "[refit] proxy not answering on ${PROXY_HOST}:${PROXY_PORT} - aborting rather than"
  echo "        fitting on whatever partial history a dead proxy returns."
  exit 1
fi

TODAY="$("$PY" -c 'import datetime;print(datetime.date.today().isoformat())')"
DATA="$ROOT/trade-analyzer/data"
ARCHIVE="$DATA/archive/$TODAY"
PREV="$(mktemp)"
trap 'rm -f "$PREV"' EXIT

if [ -f "$DATA/swing_model.json" ]; then
  mkdir -p "$ARCHIVE"
  cp -f "$DATA/swing_model.json" "$ARCHIVE/"
  if [ -f "$DATA/swing_model_report.md" ]; then
    cp -f "$DATA/swing_model_report.md" "$ARCHIVE/"
    cp -f "$DATA/swing_model_report.md" "$PREV"
  fi
  echo "[refit] archived the current artifact to $ARCHIVE"
else
  echo "[refit] no existing artifact to archive - this is a first fit."
fi

echo "[refit] fitting..."
if ! (cd "$ROOT/trade-analyzer" && "$PY" fit_swing_model.py); then
  echo "[refit] FIT FAILED OR NOT SHIPPED - the previous artifact is untouched and still live."
  REJ="$DATA/swing_model_report.rejected.md"
  if [ -s "$PREV" ] && [ -f "$REJ" ] && [ "$REJ" -nt "$PREV" ]; then
    echo
    echo "[refit] report diff: live fit vs the REJECTED fit:"
    "$PY" tools/diff_swing_report.py "$PREV" "$REJ" || true
  fi
  exit 1
fi

if [ -s "$PREV" ]; then
  echo
  echo "[refit] report diff against the prior fit:"
  "$PY" tools/diff_swing_report.py "$PREV" "$DATA/swing_model_report.md"
fi
echo "[refit] done."
