#!/usr/bin/env bash
# Wrapper for the post-close instrumentation run.
#
# Exists so a systemd timer has one thing to invoke rather than an interpreter
# plus args plus a redirect. ROOT is derived from this script's own location, so
# the checkout it lives in is the checkout it measures.
#
# Output appends to logs/flow_delta_instr.log; the report itself lands under
# options-scanner/data/flow_delta_instrumentation/<date>/.
#
# THE MANUAL PATH. The scheduled one is the systemd timer
# trading-<env>-flow-delta.timer, generated by deploy/systemd/generate_units.py
# from [slots.flow_delta] (16:00 CT, Mon..Fri). That unit calls the Python
# DIRECTLY -- it gets MEMURAI_PASSWORD from EnvironmentFile= and its output from
# the journal, so it needs neither of the two things this wrapper does. Use this
# to run the report by hand, or to backfill a day the timer missed.
#
# CADENCE IS EVERY TRADING DAY, not Mondays. The .bat this replaced said
# "Monday" in its header too, while the schtasks job that actually invoked it ran
# daily -- every weekday from 2026-08-11 to 2026-08-28 has a report, each stamped
# 15:30 CT. The header was never corrected and the Linux conversion copied the
# wrong word across. The timer now runs at 16:00 rather than 15:30, to clear the
# 15:25-15:50 live_capture window; see [slots.flow_delta] for why that matters.
#
# No holiday filter is needed anywhere: flow_delta_instrumentation.py gates on
# shared/market_calendar.is_trading_day and exits 0 on a holiday, so a timer that
# fires is not the same as a run that measures.
#
# HISTORY, because the gap it left is the reason the unit is documented so
# heavily: from the 2026-08-29 systemd migration until 2026-09-09 NOTHING
# scheduled this. The schedule had lived in Windows Task Scheduler, outside the
# repo, and the conversion replaced it with a comment. 08-31, 09-02, 09-03,
# 09-04 and 09-08 have no report and never will -- the closing chain is gone and
# cache:options:flow_alerts resets overnight.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY="$ROOT/.venv/bin/python"
LOG="$ROOT/logs/flow_delta_instr.log"
mkdir -p "$ROOT/logs"

# The report reconciles against the live channel in Redis, which needs
# MEMURAI_PASSWORD. The services get it from the units' EnvironmentFile=; a bare
# run inherits nothing, so source it the way docs/dev-prod-environments.md
# prescribes. Values in .env must stay QUOTED -- systemd takes them literally
# while bash parses them, and that disagreement is what this line walks into.
# Without it the run still exits 0 and the report just says "Not reconciled".
if [ -f "$ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  . "$ROOT/.env"
  set +a
fi

{
  echo "==== $(date '+%Y-%m-%d %H:%M:%S %Z') ===="
  "$PY" -X utf8 "$ROOT/tools/flow_delta_instrumentation.py"
  echo "exit=$?"
} >> "$LOG" 2>&1
